---
- name: Jinja2 템플릿 파일 배포
  hosts: dev
  tasks:
    - name: hosts.j2 => /etc/myhosts 파일 배포
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: "0644"