---
- name: 사용자 계정 생성
  hosts: dev, test
  gather_facts: false
  vars_files:
      - userlist.yml
      - pw.yml
  tasks:
    ###########################################################
    # 1) 그룹 추가 - adm, daemon (그룹이 있는지 먼저 확인 할 것 )
    # 2) 사용자 생성
    # 3) 
    #
    ############################################################
    - name: 사용자 생성
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ pw_developer | password_hash('sha512') }}"
        groups: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"
      when: item.username == "developer"
- name: 사용자 계정 생성
  hosts: prod
  vars_files:
      - userlist.yml
      - pw.yml
  tasks:
    - name: 사용자 생성
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ pw_developer | password_hash('sha512') }}"
        groups: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"
      when: item.username == "manager"